blank_issues_enabled: false
contact_links:
  - name: Report a bug or give feedback
    url: https://github.com/michaelmakaab/player-watchlist/discussions
    about: For bug reports, feature ideas, or general feedback
